name: XLSX_Sample
description: ''
version: 0.0.1
author: bob.welshmer@gmail.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: xlsxsample
  parentArtefactID: bobwelshmergmailcomteam
  buildSystem: wheel
  author: null
  createdAt: '2024-05-29 16:22:43'
pipelines:
  pipelines/XLSX_Sample_pipeline:
    name: XLSX_Sample_pipeline
    description: ''
    author: bob.welshmer@gmail.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-29 16:22:43'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-05-29 16:22:43'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-05-29T16:22:43.967919Z'
  name: plibMaven
  version: 7.1.102
  id: '438932062'
  createdAt: '2024-05-29T16:22:43.967919Z'
  type: plibMaven
- modifiedAt: '2024-05-29T16:22:43.967919Z'
  name: plibPypi
  version: 1.8.19
  id: '1906871951'
  createdAt: '2024-05-29T16:22:43.967919Z'
  type: plibPypi
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.14
    isDefault: true
    author: null
    createdAt: '2024-05-29 16:11:01'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.6
    isDefault: true
    author: null
    createdAt: '2024-05-29 16:11:01'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
