name: XLSX_Sample
description: ''
version: 0.0.1
author: bob.welshmer@gmail.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: xlsxsample
  parentArtefactID: bobwelshmergmailcomteam
  buildSystem: wheel
  author: null
  createdAt: '2024-05-29 16:22:43'
pipelines:
  pipelines/XLSX_Sample_pipeline:
    name: XLSX_Sample_pipeline
    description: ''
    author: bob.welshmer@gmail.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-29 16:22:43'
    datasets:
      inputs:
      - datasets/snow_customers
      - datasets/xlsx_orders
      outputs:
      - datasets/dbx_sales_rollup
    subgraphs: []
    dependencies: {}
datasets:
  datasets/xlsx_test:
    name: xlsx_test
    description: ''
    author: bob.welshmer@gmail.com
    createdAt: '2024-05-29 16:43:47'
    mode: batch
    physicalDatasets:
      DBX-Prophecy:
        fabricId: 12989
        datasetType: File
        description: ''
        author: bob.welshmer@gmail.com
        createdAt: '2024-05-29 16:43:47'
  datasets/xlsx_orders:
    name: xlsx_orders
    description: ''
    author: bob.welshmer@gmail.com
    createdAt: '2024-05-29 16:47:03'
    mode: batch
    physicalDatasets:
      DBX-Prophecy:
        fabricId: 12989
        datasetType: File
        description: ''
        author: bob.welshmer@gmail.com
        createdAt: '2024-05-29 16:47:03'
  datasets/snow_customers:
    name: snow_customers
    description: ''
    author: bob.welshmer@gmail.com
    createdAt: '2024-05-29 16:57:19'
    mode: batch
    physicalDatasets:
      DBX-Prophecy:
        fabricId: 12989
        datasetType: Warehouse
        description: ''
        author: bob.welshmer@gmail.com
        createdAt: '2024-05-29 16:57:19'
  datasets/dbx_sales_rollup:
    name: dbx_sales_rollup
    description: ''
    author: bob.welshmer@gmail.com
    createdAt: '2024-05-29 17:03:31'
    mode: batch
    physicalDatasets:
      DBX-Prophecy:
        fabricId: 12989
        datasetType: Database
        description: ''
        author: bob.welshmer@gmail.com
        createdAt: '2024-05-29 17:03:31'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-05-29 16:22:43'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-05-29T16:22:43.967919Z'
  name: plibMaven
  version: 7.1.102
  id: '438932062'
  createdAt: '2024-05-29T16:22:43.967919Z'
  type: plibMaven
  enabled: true
  entity: Project
- modifiedAt: '2024-05-29T16:22:43.967919Z'
  name: plibPypi
  version: 1.8.19
  id: '1906871951'
  createdAt: '2024-05-29T16:22:43.967919Z'
  type: plibPypi
  enabled: true
  entity: Project
- description: com.crealytics:spark-excel_2.12:3.5.0_0.20.3
  id: hXB8vprkeDmfaWcQflmjp
  editable: true
  enabled: true
  coordinates: com.crealytics:spark-excel_2.12:3.5.0_0.20.3
  type: coordinates
  name: spark-excel
  scope: Project
  package: ''
  version: ''
  exclusions: []
  entity: Project
  modifiedAt: '2024-05-29T16:24:15.677Z'
  createdAt: '2024-05-29T16:24:15.677Z'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.14
    isDefault: true
    author: null
    createdAt: '2024-05-29 16:11:01'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.6
    isDefault: true
    author: null
    createdAt: '2024-05-29 16:11:01'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
